### ISSUE TITLE
Пустые строчки не удаляются

### ISSUE THREAD

**Issue by AliusDieMorietur** [HowProgrammingWorks/Files#3]
```
'use strict';

const fs = require('fs');

const data = fs.readFileSync('1-readFileSync.js', 'utf8');
const lines = data.split('\n').filter(line => !!line);
fs.writeFileSync('1-readFileSync.txt', lines.join('\n'));


```
![image](https://user-images.githubusercontent.com/44651557/73092198-ceba4180-3ee4-11ea-95d2-21be6d4e9ae5.png)
![image](https://user-images.githubusercontent.com/44651557/73092412-3ff9f480-3ee5-11ea-9c32-91708f74ee82.png)

**Comment by lundibundi** [comment]
Could you be running this on windows perhaps? Then your newline symbol might be `\r\n` instead of just `\n` which would lead to `.filter(` expression not removing them. You can try to change the split to `.split(/\r?\n/)` to account for that.

**Comment by AliusDieMorietur** [comment]
Okay, thanks. I will try.

пт, 24 янв. 2020 г., 20:11 Denys Otrishko <notifications@github.com>:

**Comment by AliusDieMorietur** [comment]
Is there any universal solution for linux and windows?
